language: swift
os: osx
osx_image: xcode10.2
before_script:
- gem install xcpretty
- gem install xcpretty-travis-formatter
##- gem install vapor
- brew install pkg-config
- brew install libressl
- brew tap mongodb/brew
- brew install mongodb-community@3.6
- mkdir -p $PWD/data/db
- cp binaries/aapt /usr/local/bin && chmod +x /usr/local/bin/aapt
## start mongo
- mongod --dbpath $PWD/data/db --fork --syslog
- swift package generate-xcodeproj
script:
- set -o pipefail && xcodebuild -scheme Run clean test -enableCodeCoverage YES | xcpretty -f `xcpretty-travis-formatter`
after_success:
  - bash <(curl -s https://codecov.io/bash)
