language: swift
os: osx
osx_image: xcode10.2
before_script:
- gem install xcpretty
##- gem install vapor
- brew install pkg-config
- brew install libressl
- brew install mongodb
- mkdir -p $PWD/data/db
## start mongo
- mongod --dbpath $PWD/data/db --fork --syslog
- swift package generate-xcodeproj
script:
- set -o pipefail && xcodebuild -scheme Run clean test -enableCodeCoverage YES | xcpretty
after_success:
  - bash <(curl -s https://codecov.io/bash)
