language: swift
##services:
##  - mongodb
os: osx
osx_image: xcode10.2
before_script:
- gem install xcpretty
##- gem install vapor
- brew install pkg-config
- brew install libressl
- brew install mongodb
## start mongo
- mongod
## check mongo running?
- mongo
script:
- swift package generate-xcodeproj
- set -o pipefail && xcodebuild -scheme Run clean test | xcpretty
