language: swift
services:
  - mongodb
os: osx
osx_image: xcode10.2
before_script:
- gem install xcpretty
## - /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
##- gem install vapor
- brew install pkg-config
- brew install libressl
script:
- swift package generate-xcodeproj
- set -o pipefail && xcodebuild -scheme Run clean test | xcpretty
