#if !canImport(ObjectiveC)
import XCTest

extension AppTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__AppTests = [
        ("testNothing", testNothing),
    ]
}

extension ApplicationServiceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ApplicationServiceTests = [
        ("testCreateApplication", testCreateApplication),
        ("testDeleteApplication", testDeleteApplication),
        ("testExistingApp", testExistingApp),
        ("testFindApplication", testFindApplication),
        ("testUpdateApplicationAdminUsers", testUpdateApplicationAdminUsers),
    ]
}

extension ApplicationsControllerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ApplicationsControllerTests = [
        ("testAddAdminUser", testAddAdminUser),
        ("testAddAdminUserInvalid", testAddAdminUserInvalid),
        ("testAddAdminUserUnAuthorized", testAddAdminUserUnAuthorized),
        ("testAdministeredApps", testAdministeredApps),
        ("testAllApplications", testAllApplications),
        ("testAllApplicationsMultipleUsers", testAllApplicationsMultipleUsers),
        ("testAppDetail", testAppDetail),
        ("testAppDetailNotAdmin", testAppDetailNotAdmin),
        ("testAppDetailWithBranches", testAppDetailWithBranches),
        ("testApplicationIcon", testApplicationIcon),
        ("testCreate", testCreate),
        ("testCreateMultiple", testCreateMultiple),
        ("testCreateTwiceError", testCreateTwiceError),
        ("testDeleteApplication", testDeleteApplication),
        ("testDeleteApplicationKO", testDeleteApplicationKO),
        ("testFavoritesApplications", testFavoritesApplications),
        ("testFilterApplications", testFilterApplications),
        ("testFilterApplicationsBadPlatform", testFilterApplicationsBadPlatform),
        ("testMaxVersion", testMaxVersion),
        ("testMaxVersionKO", testMaxVersionKO),
        ("testMaxVersionNotActivated", testMaxVersionNotActivated),
        ("testRemoveAdminUser", testRemoveAdminUser),
        ("testRemoveAdminUserInvalid", testRemoveAdminUserInvalid),
        ("testRemoveAdminUserUnAuthorized", testRemoveAdminUserUnAuthorized),
        ("testRetrieveVersion", testRetrieveVersion),
        ("testRetrieveVersions", testRetrieveVersions),
        ("testRetrieveVersionsByBranchAndLatest", testRetrieveVersionsByBranchAndLatest),
        ("testRetrieveVersionsByBranch", testRetrieveVersionsByBranch),
        ("testRetrieveVersionsByPages", testRetrieveVersionsByPages),
        ("testRetrieveVersionsGrouped", testRetrieveVersionsGrouped),
        ("testRetrieveVersionsLatest", testRetrieveVersionsLatest),
        ("testUpdateApplication", testUpdateApplication),
        ("testUpdateApplicationNotAdmin", testUpdateApplicationNotAdmin),
    ]
}

extension ArtifactsContollerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ArtifactsContollerTests = [
        ("testBadContentType2", testBadContentType2),
        ("testBadContentType", testBadContentType),
        ("testCreateApkArtifact", testCreateApkArtifact),
        ("testCreateApkArtifactFullArgs", testCreateApkArtifactFullArgs),
        ("testCreateArtifactBadApiKey", testCreateArtifactBadApiKey),
        ("testCreateArtifactBigFile", testCreateArtifactBigFile),
        ("testCreateIpaArtifact", testCreateIpaArtifact),
        ("testCreateIpaArtifactFullArgs", testCreateIpaArtifactFullArgs),
        ("testCreateIpaArtifactWithSortIdentifier", testCreateIpaArtifactWithSortIdentifier),
        ("testCreateLastArtifact", testCreateLastArtifact),
        ("testCreateLastArtifactFullArgs", testCreateLastArtifactFullArgs),
        ("testCreateSameArtifact", testCreateSameArtifact),
        ("testCreateWithApiKey", testCreateWithApiKey),
        ("testDeleteArtifact", testDeleteArtifact),
        ("testDeleteArtifactBasApiKey", testDeleteArtifactBasApiKey),
        ("testDeleteArtifactNotFound", testDeleteArtifactNotFound),
        ("testDeleteArtifactTwice", testDeleteArtifactTwice),
        ("testDownloadAndroidDownloadFile", testDownloadAndroidDownloadFile),
        ("testDownloadInfoAndroid", testDownloadInfoAndroid),
        ("testDownloadInfoIOS", testDownloadInfoIOS),
        ("testDownloadiOSDownloadFile", testDownloadiOSDownloadFile),
        ("testDownloadiOSManifest", testDownloadiOSManifest),
        ("testInstallPageIOS", testInstallPageIOS),
    ]
}

extension ArtifactsServiceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ArtifactsServiceTests = [
        ("testAddArtifactsAndsort", testAddArtifactsAndsort),
    ]
}

extension DeployScriptTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__DeployScriptTests = [
        ("testCallAddKO", testCallAddKO),
        ("testCallDeleteKO", testCallDeleteKO),
        ("testCallDeleteNotFound", testCallDeleteNotFound),
        ("testCallFromFileOK", testCallFromFileOK),
        ("testCallFullParametersOK", testCallFullParametersOK),
    ]
}

extension LocalStorageArtifactsContollerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LocalStorageArtifactsContollerTests = [
        ("testDownloadiOSManifest", testDownloadiOSManifest),
    ]
}

extension LocalStorageServiceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__LocalStorageServiceTests = [
        ("testDeleteFile", testDeleteFile),
        ("testInitStoreFile", testInitStoreFile),
        ("testStoreBigFile", testStoreBigFile),
        ("testStoreFile", testStoreFile),
    ]
}

extension PaginationControllerTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__PaginationControllerTests = [
        ("testApplicationsPaginationEmptyResult", testApplicationsPaginationEmptyResult),
        ("testApplicationsPaginationSearchByName", testApplicationsPaginationSearchByName),
        ("testApplicationsPaginationSearchByNameBigValue", testApplicationsPaginationSearchByNameBigValue),
        ("testApplicationsPaginationSearchByNameInsensitive", testApplicationsPaginationSearchByNameInsensitive),
        ("testApplicationsPaginationSortByCreated", testApplicationsPaginationSortByCreated),
        ("testApplicationsPaginationSortByName", testApplicationsPaginationSortByName),
        ("testUsersPagination", testUsersPagination),
        ("testUsersPaginationBigValue", testUsersPaginationBigValue),
        ("testUsersPaginationSearchByEmail", testUsersPaginationSearchByEmail),
        ("testUsersPaginationSortByCreatedAscending", testUsersPaginationSortByCreatedAscending),
        ("testUsersPaginationSortByCreatedDescending", testUsersPaginationSortByCreatedDescending),
        ("testUsersPaginationSortByEmail", testUsersPaginationSortByEmail),
        ("testUsersPaginationSortByLogin", testUsersPaginationSortByLogin),
    ]
}

extension RandomTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__RandomTests = [
        ("testRandom", testRandom),
        ("testRandom2", testRandom2),
    ]
}

extension TokenInfoServiceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__TokenInfoServiceTests = [
        ("testCreateAndRetrieveToken", testCreateAndRetrieveToken),
        ("testCreateToken", testCreateToken),
        ("testExpiredDuration", testExpiredDuration),
        ("testExpiredPurge", testExpiredPurge),
        ("testPurgeAll", testPurgeAll),
    ]
}

extension UsersControllerAutomaticRegistrationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UsersControllerAutomaticRegistrationTests = [
        ("testForgotPassword", testForgotPassword),
        ("testLogin", testLogin),
        ("testRegister", testRegister),
        ("testRegisterInavlidEmailFormat", testRegisterInavlidEmailFormat),
    ]
}

extension UsersControllerNoAutomaticAndTemplatesRegistrationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UsersControllerNoAutomaticAndTemplatesRegistrationTests = [
        ("testRegisterAlternateTemplate", testRegisterAlternateTemplate),
    ]
}

extension UsersControllerNoAutomaticRegistrationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UsersControllerNoAutomaticRegistrationTests = [
        ("testActivation", testActivation),
        ("testActivationKO", testActivationKO),
        ("testForgotPassword", testForgotPassword),
        ("testForgotPasswordCheckAccountIsDisabled", testForgotPasswordCheckAccountIsDisabled),
        ("testForgotPasswordKO", testForgotPasswordKO),
        ("testLogin", testLogin),
        ("testLoginKo", testLoginKo),
        ("testLoginNotActivated", testLoginNotActivated),
        ("testMe", testMe),
        ("testMeKOBadToken", testMeKOBadToken),
        ("testMeKOWithRefreshToken", testMeKOWithRefreshToken),
        ("testRefreshLogin", testRefreshLogin),
        ("testRefreshLoginKOBadEmail", testRefreshLoginKOBadEmail),
        ("testRefreshLoginKOBadToken", testRefreshLoginKOBadToken),
        ("testRegister", testRegister),
        ("testUpdate", testUpdate),
        ("testUpdateDelete", testUpdateDelete),
        ("testUpdateNotAdmin", testUpdateNotAdmin),
        ("testUpdateOther", testUpdateOther),
        ("testUpdateWithApp", testUpdateWithApp),
    ]
}

extension UsersControllerPasswordStrengthAndDelayRegistrationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UsersControllerPasswordStrengthAndDelayRegistrationTests = [
        ("testLoginWithDelay", testLoginWithDelay),
        ("testRegisterKO", testRegisterKO),
        ("testRegisterOK", testRegisterOK),
    ]
}

extension UsersControllerWhiteDomainsRegistrationTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UsersControllerWhiteDomainsRegistrationTests = [
        ("testRegisterKO", testRegisterKO),
        ("testRegisterOK", testRegisterOK),
    ]
}

extension UsersServiceTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UsersServiceTests = [
        ("testAdminUser", testAdminUser),
        ("testCreateActivatedUser", testCreateActivatedUser),
        ("testCreateIdenticalUser", testCreateIdenticalUser),
        ("testCreateNormalUser", testCreateNormalUser),
        ("testDeleteTwice", testDeleteTwice),
        ("testLoginUser", testLoginUser),
        ("testLoginUserFailed", testLoginUserFailed),
        ("testResetUser", testResetUser),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(AppTests.__allTests__AppTests),
        testCase(ApplicationServiceTests.__allTests__ApplicationServiceTests),
        testCase(ApplicationsControllerTests.__allTests__ApplicationsControllerTests),
        testCase(ArtifactsContollerTests.__allTests__ArtifactsContollerTests),
        testCase(ArtifactsServiceTests.__allTests__ArtifactsServiceTests),
        testCase(DeployScriptTests.__allTests__DeployScriptTests),
        testCase(LocalStorageArtifactsContollerTests.__allTests__LocalStorageArtifactsContollerTests),
        testCase(LocalStorageServiceTests.__allTests__LocalStorageServiceTests),
        testCase(PaginationControllerTests.__allTests__PaginationControllerTests),
        testCase(RandomTests.__allTests__RandomTests),
        testCase(TokenInfoServiceTests.__allTests__TokenInfoServiceTests),
        testCase(UsersControllerAutomaticRegistrationTests.__allTests__UsersControllerAutomaticRegistrationTests),
        testCase(UsersControllerNoAutomaticAndTemplatesRegistrationTests.__allTests__UsersControllerNoAutomaticAndTemplatesRegistrationTests),
        testCase(UsersControllerNoAutomaticRegistrationTests.__allTests__UsersControllerNoAutomaticRegistrationTests),
        testCase(UsersControllerPasswordStrengthAndDelayRegistrationTests.__allTests__UsersControllerPasswordStrengthAndDelayRegistrationTests),
        testCase(UsersControllerWhiteDomainsRegistrationTests.__allTests__UsersControllerWhiteDomainsRegistrationTests),
        testCase(UsersServiceTests.__allTests__UsersServiceTests),
    ]
}
#endif
