name: Swift

on:
  push:
    branches: [ master,develop ]
  pull_request:
    branches: [ master ]

jobs:
  macos:

    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v2
    - run: brew install pkg-config
    - run: brew install libressl
    - run: brew tap mongodb/brew
    - run: brew install mongodb-community@3.6
    - run: mkdir -p $PWD/data/db
    - run: cp binaries/aapt /usr/local/bin && chmod +x /usr/local/bin/aapt
    - run: curl --version
    - run: python3 --version
    - run: pip3 install requests
    - run: which python3 > Ressources/python.path
    - run: python3  testDeps.py 
    - run: xcrun swift test --enable-test-discovery --sanitize=thread
      
  linux:
    services:
      mongodb:
        image: mongo:3.6
        ports:
        - 27017:27017
    container: 
      image: vapor/swift:5.2-xenial
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: swift test --enable-test-discovery --sanitize=thread
  linux_bionic:
    services:
      mongodb:
        image: mongo:3.6
        ports:
        - 27017:27017
    container: 
      image: vapor/swift:5.2-bionic
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: swift test --enable-test-discovery --sanitize=thread
      
